export const ErrorCode = {
	OK: "OK",
	UNKNOWN_ERROR: "UNKNOWN_ERROR",
	VALIDATION_ERROR: "VALIDATION_ERROR",

	ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
	ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	STAFF_NOT_FOUND: "STAFF_NOT_FOUND",
	STAFF_ROLE_NOT_FOUND: "STAFF_ROLE_NOT_FOUND",
	STAFF_EMAIL_ALREADY_EXISTS: "STAFF_EMAIL_ALREADY_EXISTS",
} as const;

export type ErrorCodeEnum = (typeof ErrorCode)[keyof typeof ErrorCode];
